//! DVC-compatible error code registry.
//!
//! The full `JID_*` set from upstream `Source/JsonModel.h` lives in the
//! sibling `jid_registry` module — that file is generated by
//! `tools/gen-jids/` and is the single source of truth for every code's
//! numeric value. Regenerate it with:
//!
//! ```sh
//! cargo run --manifest-path tools/gen-jids/Cargo.toml
//! ```
//!
//! The curated [`jid`] submodule below is a short-named alias layer for
//! the subset the engine actually references. Every alias is defined as
//! `pub const SHORT: ErrorCode = jid_registry::JID_LONG` so values can
//! never drift from upstream.

use serde::{Deserialize, Serialize};

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ErrorCode(pub u32);

impl ErrorCode {
    pub const fn new(code: u32) -> Self {
        Self(code)
    }

    pub const fn value(self) -> u32 {
        self.0
    }

    pub fn category(self) -> Category {
        match self.0 {
            1000..=1999 => Category::CharShape,
            2000..=2999 => Category::ParaShape,
            3000..=3099 => Category::Table,
            3100..=3999 => Category::Element,
            4000..=4999 => Category::Style,
            5000..=5999 => Category::Page,
            6000..=6999 => Category::Reference,
            7000..=10999 => Category::Extended,
            11000..=11999 => Category::Integrity,
            _ => Category::Unknown,
        }
    }

    pub fn text(self) -> &'static str {
        // Human-readable messages for codes the engine actively emits.
        // Each arm pulls its numeric value from the curated `jid` aliases
        // (which in turn resolve to `jid_registry` constants), so a
        // upstream JID renumbering can never silently desync the messages.
        // Unlisted codes fall through to a generic message — the full
        // registry in `jid_registry` exists so unimplemented categories
        // can still be referenced by downstream code without a placeholder
        // `u32` literal.
        //
        // `match` patterns on u32 need `const` bindings, so we surface
        // each `jid::X.value()` through a named constant here. The cost
        // is a bit of boilerplate; the win is zero numeric drift risk.
        const FONTSIZE: u32 = jid::CHAR_SHAPE_FONTSIZE.value();
        const FONT: u32 = jid::CHAR_SHAPE_FONT.value();
        const RSIZE: u32 = jid::CHAR_SHAPE_RSIZE.value();
        const RATIO: u32 = jid::CHAR_SHAPE_RATIO.value();
        const SPACING: u32 = jid::CHAR_SHAPE_SPACING.value();
        const BOLD: u32 = jid::CHAR_SHAPE_BOLD.value();
        const ITALIC: u32 = jid::CHAR_SHAPE_ITALIC.value();
        const UNDERLINE: u32 = jid::CHAR_SHAPE_UNDERLINE.value();
        const STRIKEOUT: u32 = jid::CHAR_SHAPE_STRIKEOUT.value();
        const OUTLINE: u32 = jid::CHAR_SHAPE_OUTLINE.value();
        const EMBOSS: u32 = jid::CHAR_SHAPE_EMBOSS.value();
        const ENGRAVE: u32 = jid::CHAR_SHAPE_ENGRAVE.value();
        const SHADOW: u32 = jid::CHAR_SHAPE_SHADOW.value();
        const SUPSCRIPT: u32 = jid::CHAR_SHAPE_SUPSCRIPT.value();
        const SUBSCRIPT: u32 = jid::CHAR_SHAPE_SUBSCRIPT.value();
        const SHADOWTYPE: u32 = jid::CHAR_SHAPE_SHADOWTYPE.value();
        const SHADOW_X: u32 = jid::CHAR_SHAPE_SHADOW_X.value();
        const SHADOW_Y: u32 = jid::CHAR_SHAPE_SHADOW_Y.value();
        const SHADOW_COLOR: u32 = jid::CHAR_SHAPE_SHADOW_COLOR.value();
        const KERNING: u32 = jid::CHAR_SHAPE_KERNING.value();

        const PARA_ALIGN: u32 = jid::PARA_SHAPE_ALIGN.value();
        const PARA_INDENT: u32 = jid::PARA_SHAPE_INDENT.value();
        const PARA_OUTDENT: u32 = jid::PARA_SHAPE_OUTDENT.value();
        const PARA_LINESPACING: u32 = jid::PARA_SHAPE_LINESPACING_TYPE.value();
        const PARA_LINESPACINGVALUE: u32 = jid::PARA_SHAPE_LINESPACINGVALUE.value();
        const PARA_SPACING_PARAUP: u32 = jid::PARA_SHAPE_SPACING_PARAUP.value();
        const PARA_SPACING_PARABOTTOM: u32 = jid::PARA_SHAPE_SPACING_PARABOTTOM.value();

        const TABLE_WIDTH: u32 = jid::TABLE_SIZE_WIDTH.value();
        const TABLE_HEIGHT: u32 = jid::TABLE_SIZE_HEIGHT.value();
        const TABLE_FIXED: u32 = jid::TABLE_SIZE_FIXED.value();
        const TABLE_TREAT_AS_CHAR: u32 = jid::TABLE_TREAT_AS_CHAR.value();
        const TABLE_POS: u32 = jid::TABLE_POS.value();
        const TABLE_TEXTPOS: u32 = jid::TABLE_TEXTPOS.value();
        const TABLE_MARGIN_LEFT: u32 = jid::TABLE_MARGIN_LEFT.value();
        const TABLE_MARGIN_RIGHT: u32 = jid::TABLE_MARGIN_RIGHT.value();
        const TABLE_MARGIN_TOP: u32 = jid::TABLE_MARGIN_TOP.value();
        const TABLE_MARGIN_BOTTOM: u32 = jid::TABLE_MARGIN_BOTTOM.value();
        const TABLE_CAPTION_POSITION: u32 = jid::TABLE_CAPTION_POSITION.value();
        const TABLE_CAPTION_SIZE: u32 = jid::TABLE_CAPTION_SIZE.value();
        const TABLE_CAPTION_SPACING: u32 = jid::TABLE_CAPTION_SPACING.value();
        const TABLE_BGFILL_TYPE: u32 = jid::TABLE_BGFILL_TYPE.value();
        const TABLE_BGFILL_FACECOLOR: u32 = jid::TABLE_BGFILL_FACECOLOR.value();
        const TABLE_BGFILL_PATTONCOLOR: u32 = jid::TABLE_BGFILL_PATTONCOLOR.value();
        const TABLE_BGFILL_PATTONTYPE: u32 = jid::TABLE_BGFILL_PATTONTYPE.value();
        const TABLE_BORDER: u32 = jid::TABLE_BORDER.value();
        const TABLE_BORDER_TYPE: u32 = jid::TABLE_BORDER_TYPE.value();
        const TABLE_BORDER_SIZE: u32 = jid::TABLE_BORDER_SIZE.value();
        const TABLE_BORDER_COLOR: u32 = jid::TABLE_BORDER_COLOR.value();
        const TABLE_IN_TABLE: u32 = jid::TABLE_IN_TABLE.value();

        const SPECIAL_CHARACTER: u32 = jid::SPECIAL_CHARACTER.value();
        const SPECIAL_CHAR_MINIMUM: u32 = jid::SPECIAL_CHAR_MINIMUM.value();
        const SPECIAL_CHAR_MAXIMUM: u32 = jid::SPECIAL_CHAR_MAXIMUM.value();

        const OUTLINE_NUMBERTYPE: u32 = jid::OUTLINESHAPE_NUMBERTYPE.value();
        const OUTLINE_NUMBERSHAPE: u32 = jid::OUTLINESHAPE_NUMBERSHAPE.value();
        const BULLET_SHAPES: u32 = jid::BULLET_SHAPES.value();
        const PARANUMBULLET_NUMBERTYPE: u32 = jid::PARANUMBULLET_NUMBERTYPE.value();
        const PARANUMBULLET_NUMBERSHAPE: u32 = jid::PARANUMBULLET_NUMBERSHAPE.value();

        const STYLE_PERMISSION: u32 = jid::STYLE_PERMISSION.value();
        const HYPERLINK_PERMISSION: u32 = jid::HYPERLINK_PERMISSION.value();
        const MACRO_PERMISSION: u32 = jid::MACRO_PERMISSION.value();

        const INTEGRITY_CHAR_PR_REF: u32 = jid::INTEGRITY_ORPHAN_CHAR_PR_IDREF.value();
        const INTEGRITY_PARA_PR_REF: u32 = jid::INTEGRITY_ORPHAN_PARA_PR_IDREF.value();
        const INTEGRITY_STYLE_REF: u32 = jid::INTEGRITY_ORPHAN_STYLE_IDREF.value();
        const INTEGRITY_EMPTY_LINESEG: u32 = jid::INTEGRITY_EMPTY_LINESEG.value();
        const INTEGRITY_MIMETYPE_POS: u32 = jid::INTEGRITY_MIMETYPE_POSITION.value();
        const INTEGRITY_MIMETYPE_COMP: u32 = jid::INTEGRITY_MIMETYPE_COMPRESSED.value();
        const INTEGRITY_MIMETYPE_CONT: u32 = jid::INTEGRITY_MIMETYPE_CONTENT.value();
        const INTEGRITY_BINDATA_REF_MISSING: u32 =
            jid::INTEGRITY_BINDATA_REF_MISSING_MANIFEST.value();
        const INTEGRITY_BINDATA_MANIFEST_MISSING: u32 =
            jid::INTEGRITY_BINDATA_MANIFEST_MISSING_FILE.value();
        const INTEGRITY_BINDATA_ORPHAN: u32 = jid::INTEGRITY_BINDATA_ORPHAN_FILE.value();

        match self.0 {
            FONTSIZE => "Font size does not match specification",
            FONT => "Font name does not match specification",
            RSIZE => "Relative size does not match specification",
            RATIO => "Character ratio does not match specification",
            SPACING => "Character spacing does not match specification",
            BOLD => "Bold setting does not match specification",
            ITALIC => "Italic setting does not match specification",
            UNDERLINE => "Underline setting does not match specification",
            STRIKEOUT => "Strikeout setting does not match specification",
            OUTLINE => "Outline setting does not match specification",
            EMBOSS => "Emboss setting does not match specification",
            ENGRAVE => "Engrave setting does not match specification",
            SHADOW => "Shadow setting does not match specification",
            SUPSCRIPT => "Superscript setting does not match specification",
            SUBSCRIPT => "Subscript setting does not match specification",
            SHADOWTYPE => "Shadow type does not match specification",
            SHADOW_X => "Shadow X offset does not match specification",
            SHADOW_Y => "Shadow Y offset does not match specification",
            SHADOW_COLOR => "Shadow color does not match specification",
            KERNING => "Kerning setting does not match specification",

            PARA_ALIGN => "Paragraph alignment does not match specification",
            PARA_INDENT => "Paragraph indent does not match specification",
            PARA_OUTDENT => "Paragraph outdent does not match specification",
            PARA_LINESPACING => "Line spacing type does not match specification",
            PARA_LINESPACINGVALUE => "Line spacing value does not match specification",
            PARA_SPACING_PARAUP => "Paragraph top spacing does not match specification",
            PARA_SPACING_PARABOTTOM => "Paragraph bottom spacing does not match specification",

            TABLE_WIDTH => "Table width does not match specification",
            TABLE_HEIGHT => "Table height does not match specification",
            TABLE_FIXED => "Table size-fixed setting does not match specification",
            TABLE_TREAT_AS_CHAR => "Table treatAsChar setting does not match specification",
            TABLE_POS => "Table position (text wrap) does not match specification",
            TABLE_TEXTPOS => "Table text position (text flow) does not match specification",
            TABLE_MARGIN_LEFT => "Table left margin does not match specification",
            TABLE_MARGIN_RIGHT => "Table right margin does not match specification",
            TABLE_MARGIN_TOP => "Table top margin does not match specification",
            TABLE_MARGIN_BOTTOM => "Table bottom margin does not match specification",
            TABLE_CAPTION_POSITION => "Table caption position does not match specification",
            TABLE_CAPTION_SIZE => "Table caption size does not match specification",
            TABLE_CAPTION_SPACING => "Table caption spacing does not match specification",
            TABLE_BGFILL_TYPE => "Table background fill type does not match specification",
            TABLE_BGFILL_FACECOLOR => "Table background face color does not match specification",
            TABLE_BGFILL_PATTONCOLOR => {
                "Table background pattern color does not match specification"
            }
            TABLE_BGFILL_PATTONTYPE => "Table background pattern type does not match specification",
            TABLE_BORDER => "Table border does not match specification",
            TABLE_BORDER_TYPE => "Table border type does not match specification",
            TABLE_BORDER_SIZE => "Table border size does not match specification",
            TABLE_BORDER_COLOR => "Table border color does not match specification",
            TABLE_IN_TABLE => "Table-in-table is not permitted",

            SPECIAL_CHARACTER => "Character code point outside specification range",
            SPECIAL_CHAR_MINIMUM => "Character code point below specification minimum",
            SPECIAL_CHAR_MAXIMUM => "Character code point above specification maximum",

            OUTLINE_NUMBERTYPE => "Outline numbering type does not match specification",
            OUTLINE_NUMBERSHAPE => "Outline numbering shape does not match specification",
            BULLET_SHAPES => "Bullet character not in allowed set",
            PARANUMBULLET_NUMBERTYPE => "Paragraph numbering type does not match specification",
            PARANUMBULLET_NUMBERSHAPE => "Paragraph numbering shape does not match specification",

            STYLE_PERMISSION => "Style usage is not permitted",
            HYPERLINK_PERMISSION => "Hyperlink usage is not permitted",
            MACRO_PERMISSION => "Macro usage is not permitted",

            INTEGRITY_CHAR_PR_REF => "charPrIDRef has no matching charPr in header",
            INTEGRITY_PARA_PR_REF => "paraPrIDRef has no matching paraPr in header",
            INTEGRITY_STYLE_REF => "styleIDRef has no matching style in header",
            INTEGRITY_EMPTY_LINESEG => "paragraph has text but empty lineSegArray",
            INTEGRITY_MIMETYPE_POS => "mimetype is not the first ZIP entry",
            INTEGRITY_MIMETYPE_COMP => "mimetype ZIP entry is compressed (must be STORED)",
            INTEGRITY_MIMETYPE_CONT => "mimetype content is not 'application/hwp+zip'",
            INTEGRITY_BINDATA_REF_MISSING => "binaryItemIDRef has no matching manifest entry",
            INTEGRITY_BINDATA_MANIFEST_MISSING => {
                "manifest lists a BinData item whose ZIP entry is missing"
            }
            INTEGRITY_BINDATA_ORPHAN => "ZIP BinData entry is not referenced by the manifest",

            _ => "Rule violation",
        }
    }
}

/// Curated alias layer. Every constant resolves to a value defined in
/// [`crate::jid_registry`], so these short names never drift from
/// upstream. Add aliases here as the engine grows to emit more codes.
pub mod jid {
    use super::ErrorCode;
    use crate::jid_registry as r;

    pub const CHAR_SHAPE_FONTSIZE: ErrorCode = r::JID_CHAR_SHAPE_FONTSIZE;
    pub const CHAR_SHAPE_LANGSET: ErrorCode = r::JID_CHAR_SHAPE_LANGSET;
    pub const CHAR_SHAPE_FONT: ErrorCode = r::JID_CHAR_SHAPE_FONT;
    pub const CHAR_SHAPE_RATIO: ErrorCode = r::JID_CHAR_SHAPE_RATIO;
    pub const CHAR_SHAPE_SPACING: ErrorCode = r::JID_CHAR_SHAPE_SPACING;
    pub const CHAR_SHAPE_BOLD: ErrorCode = r::JID_CHAR_SHAPE_BOLD;
    pub const CHAR_SHAPE_ITALIC: ErrorCode = r::JID_CHAR_SHAPE_ITALIC;
    pub const CHAR_SHAPE_UNDERLINE: ErrorCode = r::JID_CHAR_SHAPE_UNDERLINE;
    pub const CHAR_SHAPE_STRIKEOUT: ErrorCode = r::JID_CHAR_SHAPE_STRIKEOUT;
    pub const CHAR_SHAPE_OUTLINE: ErrorCode = r::JID_CHAR_SHAPE_OUTLINE;
    pub const CHAR_SHAPE_EMBOSS: ErrorCode = r::JID_CHAR_SHAPE_EMBOSS;
    pub const CHAR_SHAPE_ENGRAVE: ErrorCode = r::JID_CHAR_SHAPE_ENGRAVE;
    pub const CHAR_SHAPE_SHADOW: ErrorCode = r::JID_CHAR_SHAPE_SHADOW;
    pub const CHAR_SHAPE_SUPSCRIPT: ErrorCode = r::JID_CHAR_SHAPE_SUPSCRIPT;
    pub const CHAR_SHAPE_SUBSCRIPT: ErrorCode = r::JID_CHAR_SHAPE_SUBSCRIPT;
    pub const CHAR_SHAPE_SHADOWTYPE: ErrorCode = r::JID_CHAR_SHAPE_SHADOWTYPE;
    pub const CHAR_SHAPE_SHADOW_X: ErrorCode = r::JID_CHAR_SHAPE_SHADOW_X;
    pub const CHAR_SHAPE_SHADOW_Y: ErrorCode = r::JID_CHAR_SHAPE_SHADOW_Y;
    pub const CHAR_SHAPE_SHADOW_COLOR: ErrorCode = r::JID_CHAR_SHAPE_SHADOW_COLOR;
    pub const CHAR_SHAPE_RSIZE: ErrorCode = r::JID_CHAR_SHAPE_RSIZE;
    pub const CHAR_SHAPE_KERNING: ErrorCode = r::JID_CHAR_SHAPE_KERNING;
    // Upstream calls this `HORIZONTAL` (the `horizontal` attribute on
    // `<hh:align>`); keep our short name `ALIGN` for reader clarity.
    pub const PARA_SHAPE_ALIGN: ErrorCode = r::JID_PARA_SHAPE_HORIZONTAL;
    pub const PARA_SHAPE_INDENT: ErrorCode = r::JID_PARA_SHAPE_INDENT;
    pub const PARA_SHAPE_OUTDENT: ErrorCode = r::JID_PARA_SHAPE_OUTDENT;
    pub const PARA_SHAPE_LINESPACING_TYPE: ErrorCode = r::JID_PARA_SHAPE_LINESPACING;
    pub const PARA_SHAPE_LINESPACINGVALUE: ErrorCode = r::JID_PARA_SHAPE_LINESPACINGVALUE;
    pub const PARA_SHAPE_SPACING_PARAUP: ErrorCode = r::JID_PARA_SHAPE_SPACINGPARAUP;
    pub const PARA_SHAPE_SPACING_PARABOTTOM: ErrorCode = r::JID_PARA_SHAPE_SPACINGPARABOTTOM;
    pub const TABLE_SIZE_WIDTH: ErrorCode = r::JID_TABLE_SIZEWIDTH;
    pub const TABLE_SIZE_HEIGHT: ErrorCode = r::JID_TABLE_SIZEHEIGHT;
    pub const TABLE_SIZE_FIXED: ErrorCode = r::JID_TABLE_SIZEFIXED;
    pub const TABLE_POS: ErrorCode = r::JID_TABLE_POS;
    pub const TABLE_TEXTPOS: ErrorCode = r::JID_TABLE_TEXTPOS;
    pub const TABLE_BORDER: ErrorCode = r::JID_TABLE_BORDER;
    pub const TABLE_BORDER_TYPE: ErrorCode = r::JID_TABLE_BORDER_TYPE;
    pub const TABLE_BORDER_SIZE: ErrorCode = r::JID_TABLE_BORDER_SIZE;
    pub const TABLE_BORDER_COLOR: ErrorCode = r::JID_TABLE_BORDER_COLOR;
    pub const TABLE_TREAT_AS_CHAR: ErrorCode = r::JID_TABLE_TREATASCHAR;
    pub const TABLE_IN_TABLE: ErrorCode = r::JID_TABLE_TABLE_IN_TABLE;
    pub const TABLE_MARGIN_LEFT: ErrorCode = r::JID_TABLE_MARGIN_LEFT;
    pub const TABLE_MARGIN_RIGHT: ErrorCode = r::JID_TABLE_MARGIN_RIGHT;
    pub const TABLE_MARGIN_TOP: ErrorCode = r::JID_TABLE_MARGIN_TOP;
    pub const TABLE_MARGIN_BOTTOM: ErrorCode = r::JID_TABLE_MARGIN_BOTTOM;
    pub const TABLE_CAPTION_POSITION: ErrorCode = r::JID_TABLE_CAPTION_POSITION;
    pub const TABLE_CAPTION_SIZE: ErrorCode = r::JID_TABLE_CAPTION_SIZE;
    pub const TABLE_CAPTION_SPACING: ErrorCode = r::JID_TABLE_CAPTION_SPACING;
    pub const TABLE_CAPTION_SOCAPFULLSIZE: ErrorCode = r::JID_TABLE_CAPTION_SOCAPFULLSIZE;
    pub const TABLE_CAPTION_LINEWRAP: ErrorCode = r::JID_TABLE_CAPTION_LINEWRAP;
    pub const TABLE_BGFILL_TYPE: ErrorCode = r::JID_TABLE_BGFILL_TYPE;
    pub const TABLE_BGFILL_FACECOLOR: ErrorCode = r::JID_TABLE_BGFILL_FACECOLOR;
    pub const TABLE_BGFILL_PATTONCOLOR: ErrorCode = r::JID_TABLE_BGFILL_PATTONCOLOR;
    pub const TABLE_BGFILL_PATTONTYPE: ErrorCode = r::JID_TABLE_BGFILL_PATTONTYPE;
    /// Upstream `Checker::CheckSpacialCharacterToCheckList` pushes one
    /// `JID_SPECIALCHARACTER` (3100) per offending code point, regardless
    /// of whether the violation is min- or max-sided. The MINIMUM/MAXIMUM
    /// aliases exist in the registry for schema parsing but shouldn't be
    /// emitted by the engine — use `SPECIAL_CHARACTER` instead.
    pub const SPECIAL_CHARACTER: ErrorCode = r::JID_SPECIALCHARACTER;
    pub const SPECIAL_CHAR_MINIMUM: ErrorCode = r::JID_SPECIALCHARACTER_MINIMUM;
    pub const SPECIAL_CHAR_MAXIMUM: ErrorCode = r::JID_SPECIALCHARACTER_MAXIMUM;
    pub const OUTLINESHAPE_NUMBERTYPE: ErrorCode = r::JID_OUTLINESHAPE_LEVELTYPE_NUMBERTYPE;
    pub const OUTLINESHAPE_NUMBERSHAPE: ErrorCode = r::JID_OUTLINESHAPE_LEVELTYPE_NUMBERSHAPE;
    pub const BULLET_SHAPES: ErrorCode = r::JID_BULLET_SHAPES;
    pub const PARANUMBULLET_NUMBERTYPE: ErrorCode = r::JID_PARANUMBULLET_LEVELTYPE_NUMBERTYPE;
    pub const PARANUMBULLET_NUMBERSHAPE: ErrorCode = r::JID_PARANUMBULLET_LEVELTYPE_NUMBERSHAPE;
    pub const STYLE_PERMISSION: ErrorCode = r::JID_STYLE_PERMISSION;
    pub const HYPERLINK_PERMISSION: ErrorCode = r::JID_HYPERLINK_PERMISSION;
    pub const MACRO_PERMISSION: ErrorCode = r::JID_MACRO_PERMISSION;

    // ─── polaris-original: structural integrity (11000-11999) ─────────
    // Not in upstream JsonModel.h. These catch cross-reference and
    // container-level defects that DVC's rule system doesn't address —
    // e.g. a `charPrIDRef` in the body that has no matching `<hh:charPr>`,
    // an image referenced by the body but missing from the manifest, a
    // `mimetype` entry that isn't the first ZIP member. Common in HWPX
    // generated by hand or by LLMs. Filtered out under `CheckProfile::
    // DvcStrict` so byte parity with DVC.exe stays clean.

    /// Section's `charPrIDRef` has no matching `<hh:charPr id=…>` in
    /// the header → character styling is undefined.
    pub const INTEGRITY_ORPHAN_CHAR_PR_IDREF: ErrorCode = ErrorCode::new(11001);
    /// Section's `paraPrIDRef` has no matching `<hh:paraPr id=…>` in
    /// the header.
    pub const INTEGRITY_ORPHAN_PARA_PR_IDREF: ErrorCode = ErrorCode::new(11002);
    /// Paragraph's `styleIDRef` has no matching `<hh:style id=…>` in
    /// the header.
    pub const INTEGRITY_ORPHAN_STYLE_IDREF: ErrorCode = ErrorCode::new(11003);
    /// Paragraph carries text but its `<hp:linesegarray>` is empty —
    /// pagination / editing reliability at risk.
    pub const INTEGRITY_EMPTY_LINESEG: ErrorCode = ErrorCode::new(11004);

    /// `mimetype` isn't the first ZIP entry.
    pub const INTEGRITY_MIMETYPE_POSITION: ErrorCode = ErrorCode::new(11010);
    /// `mimetype` entry is compressed (must be STORED per HWPX spec).
    pub const INTEGRITY_MIMETYPE_COMPRESSED: ErrorCode = ErrorCode::new(11011);
    /// `mimetype` content isn't `application/hwp+zip`.
    pub const INTEGRITY_MIMETYPE_CONTENT: ErrorCode = ErrorCode::new(11012);

    /// Section references a `binaryItemIDRef` with no matching
    /// `<opf:item id=…>` in the manifest.
    pub const INTEGRITY_BINDATA_REF_MISSING_MANIFEST: ErrorCode = ErrorCode::new(11020);
    /// Manifest lists a BinData item whose ZIP entry is absent.
    pub const INTEGRITY_BINDATA_MANIFEST_MISSING_FILE: ErrorCode = ErrorCode::new(11021);
    /// ZIP contains a `BinData/*` entry that no manifest item points
    /// at — orphan binary asset.
    pub const INTEGRITY_BINDATA_ORPHAN_FILE: ErrorCode = ErrorCode::new(11022);
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Category {
    CharShape,
    ParaShape,
    Table,
    Element,
    Style,
    Page,
    Reference,
    Extended,
    /// polaris-original: structural integrity checks (cross-reference
    /// consistency, ZIP-container invariants, manifest↔BinData sync).
    /// Not in upstream `JsonModel.h`. 11000-11999.
    Integrity,
    Unknown,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn category_boundaries() {
        assert_eq!(ErrorCode::new(1000).category(), Category::CharShape);
        assert_eq!(ErrorCode::new(2500).category(), Category::ParaShape);
        assert_eq!(ErrorCode::new(3050).category(), Category::Table);
        assert_eq!(ErrorCode::new(3500).category(), Category::Element);
        assert_eq!(ErrorCode::new(10999).category(), Category::Extended);
        assert_eq!(ErrorCode::new(999).category(), Category::Unknown);
    }

    #[test]
    fn serde_is_transparent_u32() {
        let code = ErrorCode::new(1001);
        let s = serde_json::to_string(&code).unwrap();
        assert_eq!(s, "1001");
        let back: ErrorCode = serde_json::from_str("1001").unwrap();
        assert_eq!(back, code);
    }

    /// Sanity: the aliased short names resolve to the same integer values
    /// the engine historically used. A regression here flags a naming
    /// mismatch against the upstream-generated registry.
    #[test]
    fn curated_aliases_match_expected_values() {
        assert_eq!(jid::CHAR_SHAPE_FONTSIZE.value(), 1001);
        assert_eq!(jid::CHAR_SHAPE_FONT.value(), 1004);
        assert_eq!(jid::CHAR_SHAPE_BOLD.value(), 1009);
        assert_eq!(jid::PARA_SHAPE_ALIGN.value(), 2001);
        assert_eq!(jid::PARA_SHAPE_LINESPACINGVALUE.value(), 2008);
        assert_eq!(jid::TABLE_BORDER.value(), 3031);
        assert_eq!(jid::TABLE_BORDER_TYPE.value(), 3033);
        assert_eq!(jid::TABLE_IN_TABLE.value(), 3056);
        assert_eq!(jid::SPECIAL_CHAR_MINIMUM.value(), 3101);
        assert_eq!(jid::OUTLINESHAPE_NUMBERTYPE.value(), 3206);
        assert_eq!(jid::BULLET_SHAPES.value(), 3304);
        assert_eq!(jid::PARANUMBULLET_NUMBERSHAPE.value(), 3407);
        assert_eq!(jid::STYLE_PERMISSION.value(), 3502);
        assert_eq!(jid::HYPERLINK_PERMISSION.value(), 6901);
        assert_eq!(jid::MACRO_PERMISSION.value(), 7001);
    }

    /// Coverage anchor: the generated registry must expose every code
    /// the curated alias layer points at. Drift here means the generator
    /// or upstream header dropped something we still reference.
    #[test]
    fn registry_covers_curated_aliases() {
        // Spot-check a handful of aliases against the generated module.
        use crate::jid_registry as r;
        assert_eq!(jid::TABLE_BORDER_TYPE, r::JID_TABLE_BORDER_TYPE);
        assert_eq!(jid::BULLET_SHAPES, r::JID_BULLET_SHAPES);
        assert_eq!(jid::MACRO_PERMISSION, r::JID_MACRO_PERMISSION);
    }
}
