//! DVC-compatible error code registry.
//!
//! The full `JID_*` set from upstream `Source/JsonModel.h` lives in the
//! sibling `jid_registry` module — that file is generated by
//! `tools/gen-jids/` and is the single source of truth for every code's
//! numeric value. Regenerate it with:
//!
//! ```sh
//! cargo run --manifest-path tools/gen-jids/Cargo.toml
//! ```
//!
//! The curated [`jid`] submodule below is a short-named alias layer for
//! the subset the engine actually references. Every alias is defined as
//! `pub const SHORT: ErrorCode = jid_registry::JID_LONG` so values can
//! never drift from upstream.

use serde::{Deserialize, Serialize};

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ErrorCode(pub u32);

impl ErrorCode {
    pub const fn new(code: u32) -> Self {
        Self(code)
    }

    pub const fn value(self) -> u32 {
        self.0
    }

    pub fn category(self) -> Category {
        match self.0 {
            1000..=1999 => Category::CharShape,
            2000..=2999 => Category::ParaShape,
            3000..=3099 => Category::Table,
            3100..=3999 => Category::Element,
            4000..=4999 => Category::Style,
            5000..=5999 => Category::Page,
            6000..=6999 => Category::Reference,
            7000..=10999 => Category::Extended,
            _ => Category::Unknown,
        }
    }

    pub fn text(self) -> &'static str {
        // Human-readable messages for codes the engine actively emits.
        // Unlisted codes fall through to a generic message — the full
        // registry in `jid_registry` exists so unimplemented categories
        // can still be referenced by downstream code without a placeholder
        // `u32` literal.
        match self.0 {
            1001 => "Font size does not match specification",
            1004 => "Font name does not match specification",
            1007 => "Character ratio does not match specification",
            1008 => "Character spacing does not match specification",
            1009 => "Bold setting does not match specification",
            1010 => "Italic setting does not match specification",
            1011 => "Underline setting does not match specification",
            1012 => "Strikeout setting does not match specification",
            1013 => "Outline setting does not match specification",
            1014 => "Emboss setting does not match specification",
            1015 => "Engrave setting does not match specification",
            1016 => "Shadow setting does not match specification",
            1017 => "Superscript setting does not match specification",
            1018 => "Subscript setting does not match specification",
            1019 => "Shadow type does not match specification",
            1020 => "Shadow X offset does not match specification",
            1021 => "Shadow Y offset does not match specification",
            1022 => "Shadow color does not match specification",
            2001 => "Paragraph alignment does not match specification",
            2005 => "Paragraph indent does not match specification",
            2006 => "Paragraph outdent does not match specification",
            2007 => "Line spacing type does not match specification",
            2008 => "Line spacing value does not match specification",
            2009 => "Paragraph top spacing does not match specification",
            2010 => "Paragraph bottom spacing does not match specification",
            3001 => "Table width does not match specification",
            3002 => "Table height does not match specification",
            3022 => "Table left margin does not match specification",
            3023 => "Table right margin does not match specification",
            3024 => "Table top margin does not match specification",
            3025 => "Table bottom margin does not match specification",
            3026 => "Table caption position does not match specification",
            3027 => "Table caption size does not match specification",
            3028 => "Table caption spacing does not match specification",
            3037 => "Table background fill type does not match specification",
            3038 => "Table background face color does not match specification",
            3039 => "Table background pattern color does not match specification",
            3040 => "Table background pattern type does not match specification",
            3031 => "Table border does not match specification",
            3033 => "Table border type does not match specification",
            3034 => "Table border size does not match specification",
            3035 => "Table border color does not match specification",
            3056 => "Table-in-table is not permitted",
            3101 => "Character code point below specification minimum",
            3102 => "Character code point above specification maximum",
            3206 => "Outline numbering type does not match specification",
            3207 => "Outline numbering shape does not match specification",
            3304 => "Bullet character not in allowed set",
            3406 => "Paragraph numbering type does not match specification",
            3407 => "Paragraph numbering shape does not match specification",
            3502 => "Style usage is not permitted",
            6901 => "Hyperlink usage is not permitted",
            7001 => "Macro usage is not permitted",
            _ => "Rule violation",
        }
    }
}

/// Curated alias layer. Every constant resolves to a value defined in
/// [`crate::jid_registry`], so these short names never drift from
/// upstream. Add aliases here as the engine grows to emit more codes.
pub mod jid {
    use super::ErrorCode;
    use crate::jid_registry as r;

    pub const CHAR_SHAPE_FONTSIZE: ErrorCode = r::JID_CHAR_SHAPE_FONTSIZE;
    pub const CHAR_SHAPE_LANGSET: ErrorCode = r::JID_CHAR_SHAPE_LANGSET;
    pub const CHAR_SHAPE_FONT: ErrorCode = r::JID_CHAR_SHAPE_FONT;
    pub const CHAR_SHAPE_RATIO: ErrorCode = r::JID_CHAR_SHAPE_RATIO;
    pub const CHAR_SHAPE_SPACING: ErrorCode = r::JID_CHAR_SHAPE_SPACING;
    pub const CHAR_SHAPE_BOLD: ErrorCode = r::JID_CHAR_SHAPE_BOLD;
    pub const CHAR_SHAPE_ITALIC: ErrorCode = r::JID_CHAR_SHAPE_ITALIC;
    pub const CHAR_SHAPE_UNDERLINE: ErrorCode = r::JID_CHAR_SHAPE_UNDERLINE;
    pub const CHAR_SHAPE_STRIKEOUT: ErrorCode = r::JID_CHAR_SHAPE_STRIKEOUT;
    pub const CHAR_SHAPE_OUTLINE: ErrorCode = r::JID_CHAR_SHAPE_OUTLINE;
    pub const CHAR_SHAPE_EMBOSS: ErrorCode = r::JID_CHAR_SHAPE_EMBOSS;
    pub const CHAR_SHAPE_ENGRAVE: ErrorCode = r::JID_CHAR_SHAPE_ENGRAVE;
    pub const CHAR_SHAPE_SHADOW: ErrorCode = r::JID_CHAR_SHAPE_SHADOW;
    pub const CHAR_SHAPE_SUPSCRIPT: ErrorCode = r::JID_CHAR_SHAPE_SUPSCRIPT;
    pub const CHAR_SHAPE_SUBSCRIPT: ErrorCode = r::JID_CHAR_SHAPE_SUBSCRIPT;
    pub const CHAR_SHAPE_SHADOWTYPE: ErrorCode = r::JID_CHAR_SHAPE_SHADOWTYPE;
    pub const CHAR_SHAPE_SHADOW_X: ErrorCode = r::JID_CHAR_SHAPE_SHADOW_X;
    pub const CHAR_SHAPE_SHADOW_Y: ErrorCode = r::JID_CHAR_SHAPE_SHADOW_Y;
    pub const CHAR_SHAPE_SHADOW_COLOR: ErrorCode = r::JID_CHAR_SHAPE_SHADOW_COLOR;
    // Upstream calls this `HORIZONTAL` (the `horizontal` attribute on
    // `<hh:align>`); keep our short name `ALIGN` for reader clarity.
    pub const PARA_SHAPE_ALIGN: ErrorCode = r::JID_PARA_SHAPE_HORIZONTAL;
    pub const PARA_SHAPE_INDENT: ErrorCode = r::JID_PARA_SHAPE_INDENT;
    pub const PARA_SHAPE_OUTDENT: ErrorCode = r::JID_PARA_SHAPE_OUTDENT;
    pub const PARA_SHAPE_LINESPACING_TYPE: ErrorCode = r::JID_PARA_SHAPE_LINESPACING;
    pub const PARA_SHAPE_LINESPACINGVALUE: ErrorCode = r::JID_PARA_SHAPE_LINESPACINGVALUE;
    pub const PARA_SHAPE_SPACING_PARAUP: ErrorCode = r::JID_PARA_SHAPE_SPACINGPARAUP;
    pub const PARA_SHAPE_SPACING_PARABOTTOM: ErrorCode = r::JID_PARA_SHAPE_SPACINGPARABOTTOM;
    pub const TABLE_SIZE_WIDTH: ErrorCode = r::JID_TABLE_SIZEWIDTH;
    pub const TABLE_SIZE_HEIGHT: ErrorCode = r::JID_TABLE_SIZEHEIGHT;
    pub const TABLE_BORDER: ErrorCode = r::JID_TABLE_BORDER;
    pub const TABLE_BORDER_TYPE: ErrorCode = r::JID_TABLE_BORDER_TYPE;
    pub const TABLE_BORDER_SIZE: ErrorCode = r::JID_TABLE_BORDER_SIZE;
    pub const TABLE_BORDER_COLOR: ErrorCode = r::JID_TABLE_BORDER_COLOR;
    pub const TABLE_TREAT_AS_CHAR: ErrorCode = r::JID_TABLE_TREATASCHAR;
    pub const TABLE_IN_TABLE: ErrorCode = r::JID_TABLE_TABLE_IN_TABLE;
    pub const TABLE_MARGIN_LEFT: ErrorCode = r::JID_TABLE_MARGIN_LEFT;
    pub const TABLE_MARGIN_RIGHT: ErrorCode = r::JID_TABLE_MARGIN_RIGHT;
    pub const TABLE_MARGIN_TOP: ErrorCode = r::JID_TABLE_MARGIN_TOP;
    pub const TABLE_MARGIN_BOTTOM: ErrorCode = r::JID_TABLE_MARGIN_BOTTOM;
    pub const TABLE_CAPTION_POSITION: ErrorCode = r::JID_TABLE_CAPTION_POSITION;
    pub const TABLE_CAPTION_SIZE: ErrorCode = r::JID_TABLE_CAPTION_SIZE;
    pub const TABLE_CAPTION_SPACING: ErrorCode = r::JID_TABLE_CAPTION_SPACING;
    pub const TABLE_CAPTION_SOCAPFULLSIZE: ErrorCode = r::JID_TABLE_CAPTION_SOCAPFULLSIZE;
    pub const TABLE_CAPTION_LINEWRAP: ErrorCode = r::JID_TABLE_CAPTION_LINEWRAP;
    pub const TABLE_BGFILL_TYPE: ErrorCode = r::JID_TABLE_BGFILL_TYPE;
    pub const TABLE_BGFILL_FACECOLOR: ErrorCode = r::JID_TABLE_BGFILL_FACECOLOR;
    pub const TABLE_BGFILL_PATTONCOLOR: ErrorCode = r::JID_TABLE_BGFILL_PATTONCOLOR;
    pub const TABLE_BGFILL_PATTONTYPE: ErrorCode = r::JID_TABLE_BGFILL_PATTONTYPE;
    pub const SPECIAL_CHAR_MINIMUM: ErrorCode = r::JID_SPECIALCHARACTER_MINIMUM;
    pub const SPECIAL_CHAR_MAXIMUM: ErrorCode = r::JID_SPECIALCHARACTER_MAXIMUM;
    pub const OUTLINESHAPE_NUMBERTYPE: ErrorCode = r::JID_OUTLINESHAPE_LEVELTYPE_NUMBERTYPE;
    pub const OUTLINESHAPE_NUMBERSHAPE: ErrorCode = r::JID_OUTLINESHAPE_LEVELTYPE_NUMBERSHAPE;
    pub const BULLET_SHAPES: ErrorCode = r::JID_BULLET_SHAPES;
    pub const PARANUMBULLET_NUMBERTYPE: ErrorCode = r::JID_PARANUMBULLET_LEVELTYPE_NUMBERTYPE;
    pub const PARANUMBULLET_NUMBERSHAPE: ErrorCode = r::JID_PARANUMBULLET_LEVELTYPE_NUMBERSHAPE;
    pub const STYLE_PERMISSION: ErrorCode = r::JID_STYLE_PERMISSION;
    pub const HYPERLINK_PERMISSION: ErrorCode = r::JID_HYPERLINK_PERMISSION;
    pub const MACRO_PERMISSION: ErrorCode = r::JID_MACRO_PERMISSION;
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Category {
    CharShape,
    ParaShape,
    Table,
    Element,
    Style,
    Page,
    Reference,
    Extended,
    Unknown,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn category_boundaries() {
        assert_eq!(ErrorCode::new(1000).category(), Category::CharShape);
        assert_eq!(ErrorCode::new(2500).category(), Category::ParaShape);
        assert_eq!(ErrorCode::new(3050).category(), Category::Table);
        assert_eq!(ErrorCode::new(3500).category(), Category::Element);
        assert_eq!(ErrorCode::new(10999).category(), Category::Extended);
        assert_eq!(ErrorCode::new(999).category(), Category::Unknown);
    }

    #[test]
    fn serde_is_transparent_u32() {
        let code = ErrorCode::new(1001);
        let s = serde_json::to_string(&code).unwrap();
        assert_eq!(s, "1001");
        let back: ErrorCode = serde_json::from_str("1001").unwrap();
        assert_eq!(back, code);
    }

    /// Sanity: the aliased short names resolve to the same integer values
    /// the engine historically used. A regression here flags a naming
    /// mismatch against the upstream-generated registry.
    #[test]
    fn curated_aliases_match_expected_values() {
        assert_eq!(jid::CHAR_SHAPE_FONTSIZE.value(), 1001);
        assert_eq!(jid::CHAR_SHAPE_FONT.value(), 1004);
        assert_eq!(jid::CHAR_SHAPE_BOLD.value(), 1009);
        assert_eq!(jid::PARA_SHAPE_ALIGN.value(), 2001);
        assert_eq!(jid::PARA_SHAPE_LINESPACINGVALUE.value(), 2008);
        assert_eq!(jid::TABLE_BORDER.value(), 3031);
        assert_eq!(jid::TABLE_BORDER_TYPE.value(), 3033);
        assert_eq!(jid::TABLE_IN_TABLE.value(), 3056);
        assert_eq!(jid::SPECIAL_CHAR_MINIMUM.value(), 3101);
        assert_eq!(jid::OUTLINESHAPE_NUMBERTYPE.value(), 3206);
        assert_eq!(jid::BULLET_SHAPES.value(), 3304);
        assert_eq!(jid::PARANUMBULLET_NUMBERSHAPE.value(), 3407);
        assert_eq!(jid::STYLE_PERMISSION.value(), 3502);
        assert_eq!(jid::HYPERLINK_PERMISSION.value(), 6901);
        assert_eq!(jid::MACRO_PERMISSION.value(), 7001);
    }

    /// Coverage anchor: the generated registry must expose every code
    /// the curated alias layer points at. Drift here means the generator
    /// or upstream header dropped something we still reference.
    #[test]
    fn registry_covers_curated_aliases() {
        // Spot-check a handful of aliases against the generated module.
        use crate::jid_registry as r;
        assert_eq!(jid::TABLE_BORDER_TYPE, r::JID_TABLE_BORDER_TYPE);
        assert_eq!(jid::BULLET_SHAPES, r::JID_BULLET_SHAPES);
        assert_eq!(jid::MACRO_PERMISSION, r::JID_MACRO_PERMISSION);
    }
}
