//! Parse `third_party/dvc-upstream/Source/JsonModel.h` and emit every
//! `JID_*` constant into `crates/polaris-rhwpdvc-core/src/jid_registry.rs`.
//!
//! Usage (from repo root):
//!
//! ```sh
//! cargo run --manifest-path tools/gen-jids/Cargo.toml
//! ```
//!
//! The upstream header uses two shapes:
//!
//! - `#define JID_FOO  1000`                  — literal integer
//! - `#define JID_FOO_BAR  JID_FOO+5`         — symbol + offset
//!
//! We resolve both with a two-pass symbol table: first seed literal
//! values, then iteratively resolve `SYMBOL + N` expressions until no
//! more progress is possible. The emitted file is deterministic: entries
//! are grouped by top-level prefix (`CHAR_SHAPE`, `PARA_SHAPE`, …) in
//! original declaration order and flushed with a stable header comment.

use std::collections::{BTreeMap, HashMap};
use std::path::PathBuf;

const HEADER: &str = "// Generated by tools/gen-jids/. Do not edit by hand.\n\
// Source: third_party/dvc-upstream/Source/JsonModel.h\n\
//\n\
// Regenerate with:\n\
//   cargo run --manifest-path tools/gen-jids/Cargo.toml\n\n\
//! Full DVC JID registry — every `#define JID_*` from the upstream\n\
//! header, resolved to a `u32`. The curated `jid` module in\n\
//! `error_codes.rs` re-exports the subset the engine currently uses.\n\n\
use crate::error_codes::ErrorCode;\n\n";

fn main() {
    let root = repo_root();
    let header_path = root
        .join("third_party")
        .join("dvc-upstream")
        .join("Source")
        .join("JsonModel.h");
    let out_path = root
        .join("crates")
        .join("polaris-rhwpdvc-core")
        .join("src")
        .join("jid_registry.rs");

    let source = std::fs::read_to_string(&header_path)
        .unwrap_or_else(|e| panic!("read {}: {}", header_path.display(), e));

    let entries = parse(&source);
    let resolved = resolve(&entries);
    let rendered = render(&entries, &resolved);

    std::fs::write(&out_path, rendered.as_bytes())
        .unwrap_or_else(|e| panic!("write {}: {}", out_path.display(), e));

    println!(
        "wrote {} JID constants to {}",
        resolved.len(),
        out_path.display()
    );
}

/// One parsed `#define JID_*` line. `rhs` is the raw right-hand side
/// exactly as written (trimmed); we interpret it later.
#[derive(Debug, Clone)]
struct Entry {
    name: String,
    rhs: String,
    /// Source-order index, used for grouping output into the same order
    /// as the upstream header.
    order: usize,
}

fn parse(source: &str) -> Vec<Entry> {
    let mut out = Vec::new();
    for (i, line) in source.lines().enumerate() {
        let trimmed = strip_line_comment(line).trim_start();
        let Some(rest) = trimmed.strip_prefix("#define") else {
            continue;
        };
        let rest = rest.trim_start();
        let Some(after_name) = rest.strip_prefix("JID_") else {
            continue;
        };
        // Split name and RHS on the first whitespace run.
        let split_at = after_name
            .find(|c: char| c.is_whitespace())
            .unwrap_or(after_name.len());
        let tail_name = &after_name[..split_at];
        let rhs_raw = after_name[split_at..].trim();
        if tail_name.is_empty() || rhs_raw.is_empty() {
            continue;
        }
        let name = format!("JID_{tail_name}");
        // Strip any trailing line-continuation backslash.
        let rhs = rhs_raw.trim_end_matches('\\').trim().to_string();
        out.push(Entry {
            name,
            rhs,
            order: i,
        });
    }
    out
}

fn strip_line_comment(line: &str) -> &str {
    if let Some(pos) = line.find("//") {
        &line[..pos]
    } else {
        line
    }
}

fn resolve(entries: &[Entry]) -> HashMap<String, u32> {
    let mut resolved: HashMap<String, u32> = HashMap::new();

    // Seed literal-int entries first.
    let mut unresolved: Vec<(String, String)> = Vec::new();
    for e in entries {
        match eval_literal(&e.rhs) {
            Some(v) => {
                resolved.insert(e.name.clone(), v);
            }
            None => {
                unresolved.push((e.name.clone(), e.rhs.clone()));
            }
        }
    }

    // Fixed-point iteration on symbol+offset expressions.
    loop {
        let before = resolved.len();
        unresolved.retain(|(name, rhs)| match eval_symbolic(rhs, &resolved) {
            Some(v) => {
                resolved.insert(name.clone(), v);
                false
            }
            None => true,
        });
        if resolved.len() == before {
            break;
        }
    }

    if !unresolved.is_empty() {
        eprintln!("warning: {} unresolved JID defines:", unresolved.len());
        for (n, r) in &unresolved {
            eprintln!("  {} = {}", n, r);
        }
    }

    resolved
}

fn eval_literal(rhs: &str) -> Option<u32> {
    let t = rhs.trim();
    t.parse::<u32>().ok()
}

/// Handles `SYMBOL`, `SYMBOL+N`, `SYMBOL-N`, with whitespace variations.
fn eval_symbolic(rhs: &str, table: &HashMap<String, u32>) -> Option<u32> {
    let t: String = rhs.chars().filter(|c| !c.is_whitespace()).collect();
    if let Some(idx) = t.find('+') {
        let (a, b) = t.split_at(idx);
        let b = &b[1..];
        let base = lookup(table, a)?;
        let offset: i64 = b.parse().ok()?;
        return (base as i64 + offset).try_into().ok();
    }
    if let Some(idx) = t.find('-') {
        // Skip a leading '-' (shouldn't happen for these headers, but safe).
        if idx == 0 {
            return None;
        }
        let (a, b) = t.split_at(idx);
        let b = &b[1..];
        let base = lookup(table, a)?;
        let offset: i64 = b.parse().ok()?;
        return (base as i64 - offset).try_into().ok();
    }
    lookup(table, &t)
}

fn lookup(table: &HashMap<String, u32>, name: &str) -> Option<u32> {
    // Match both `JID_CHAR_SHAPE` and `CHAR_SHAPE` (defensive).
    if let Some(v) = table.get(name) {
        return Some(*v);
    }
    if !name.starts_with("JID_") {
        if let Some(v) = table.get(&format!("JID_{name}")) {
            return Some(*v);
        }
    }
    None
}

fn render(entries: &[Entry], resolved: &HashMap<String, u32>) -> String {
    // Group by top-level prefix (everything between `JID_` and the next `_`).
    let mut groups: BTreeMap<String, Vec<&Entry>> = BTreeMap::new();
    for e in entries {
        if !resolved.contains_key(&e.name) {
            continue;
        }
        let tail = e.name.strip_prefix("JID_").unwrap_or(&e.name);
        let prefix = tail.split('_').next().unwrap_or(tail).to_string();
        groups.entry(prefix).or_default().push(e);
    }
    for list in groups.values_mut() {
        list.sort_by_key(|e| e.order);
    }

    let mut out = String::new();
    out.push_str(HEADER);

    for (prefix, list) in &groups {
        out.push_str(&format!("// ---- {prefix} ----\n"));
        for e in list {
            let v = resolved[&e.name];
            out.push_str(&format!(
                "pub const {name}: ErrorCode = ErrorCode::new({v});\n",
                name = e.name
            ));
        }
        out.push('\n');
    }
    out
}

fn repo_root() -> PathBuf {
    // The tool's CARGO_MANIFEST_DIR is tools/gen-jids; its two parents is
    // the repo root.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("repo root")
        .to_path_buf()
}
