// Generated by tools/gen-jids/. Do not edit by hand.
// Source: third_party/dvc-upstream/Source/JsonModel.h
//
// Regenerate with:
//   cargo run --manifest-path tools/gen-jids/Cargo.toml

//! Full DVC JID registry — every `#define JID_*` from the upstream
//! header, resolved to a `u32`. The curated `jid` module in
//! `error_codes.rs` re-exports the subset the engine currently uses.

use crate::error_codes::ErrorCode;

// ---- BOOKMARK ----
pub const JID_BOOKMARK: ErrorCode = ErrorCode::new(6800);

// ---- BULLET ----
pub const JID_BULLET: ErrorCode = ErrorCode::new(3300);
pub const JID_BULLET_TYPE: ErrorCode = ErrorCode::new(3301);
pub const JID_BULLET_CHECKTYPE: ErrorCode = ErrorCode::new(3302);
pub const JID_BULLET_CODE: ErrorCode = ErrorCode::new(3303);
pub const JID_BULLET_SHAPES: ErrorCode = ErrorCode::new(3304);
pub const JID_BULLET_END: ErrorCode = ErrorCode::new(3399);

// ---- CHAR ----
pub const JID_CHAR_SHAPE: ErrorCode = ErrorCode::new(1000);
pub const JID_CHAR_SHAPE_FONTSIZE: ErrorCode = ErrorCode::new(1001);
pub const JID_CHAR_SHAPE_LANGSET: ErrorCode = ErrorCode::new(1002);
pub const JID_CHAR_SHAPE_LANG: ErrorCode = ErrorCode::new(1003);
pub const JID_CHAR_SHAPE_FONT: ErrorCode = ErrorCode::new(1004);
pub const JID_CHAR_SHAPE_RSIZE: ErrorCode = ErrorCode::new(1005);
pub const JID_CHAR_SHAPE_POSITION: ErrorCode = ErrorCode::new(1006);
pub const JID_CHAR_SHAPE_RATIO: ErrorCode = ErrorCode::new(1007);
pub const JID_CHAR_SHAPE_SPACING: ErrorCode = ErrorCode::new(1008);
pub const JID_CHAR_SHAPE_BOLD: ErrorCode = ErrorCode::new(1009);
pub const JID_CHAR_SHAPE_ITALIC: ErrorCode = ErrorCode::new(1010);
pub const JID_CHAR_SHAPE_UNDERLINE: ErrorCode = ErrorCode::new(1011);
pub const JID_CHAR_SHAPE_STRIKEOUT: ErrorCode = ErrorCode::new(1012);
pub const JID_CHAR_SHAPE_OUTLINE: ErrorCode = ErrorCode::new(1013);
pub const JID_CHAR_SHAPE_EMBOSS: ErrorCode = ErrorCode::new(1014);
pub const JID_CHAR_SHAPE_ENGRAVE: ErrorCode = ErrorCode::new(1015);
pub const JID_CHAR_SHAPE_SHADOW: ErrorCode = ErrorCode::new(1016);
pub const JID_CHAR_SHAPE_SUPSCRIPT: ErrorCode = ErrorCode::new(1017);
pub const JID_CHAR_SHAPE_SUBSCRIPT: ErrorCode = ErrorCode::new(1018);
pub const JID_CHAR_SHAPE_SHADOWTYPE: ErrorCode = ErrorCode::new(1019);
pub const JID_CHAR_SHAPE_SHADOW_X: ErrorCode = ErrorCode::new(1020);
pub const JID_CHAR_SHAPE_SHADOW_Y: ErrorCode = ErrorCode::new(1021);
pub const JID_CHAR_SHAPE_SHADOW_COLOR: ErrorCode = ErrorCode::new(1022);
pub const JID_CHAR_SHAPE_UNDERLINE_POSITOION: ErrorCode = ErrorCode::new(1023);
pub const JID_CHAR_SHAPE_UNDERLINE_SHAPE: ErrorCode = ErrorCode::new(1024);
pub const JID_CHAR_SHAPE_UNDERLINE_COLOR: ErrorCode = ErrorCode::new(1025);
pub const JID_CHAR_SHAPE_STRIKEOUT_SHAPE: ErrorCode = ErrorCode::new(1026);
pub const JID_CHAR_SHAPE_STRIKEOUT_COLOR: ErrorCode = ErrorCode::new(1027);
pub const JID_CHAR_SHAPE_OUTLINETYPE: ErrorCode = ErrorCode::new(1028);
pub const JID_CHAR_SHAPE_EMPTYSPACE: ErrorCode = ErrorCode::new(1029);
pub const JID_CHAR_SHAPE_POINT: ErrorCode = ErrorCode::new(1030);
pub const JID_CHAR_SHAPE_KERNING: ErrorCode = ErrorCode::new(1031);
pub const JID_CHAR_SHAPE_BG_BORDER: ErrorCode = ErrorCode::new(1032);
pub const JID_CHAR_SHAPE_BG_BORDER_POSITION: ErrorCode = ErrorCode::new(1033);
pub const JID_CHAR_SHAPE_BG_BORDER_BORDERTYPE: ErrorCode = ErrorCode::new(1034);
pub const JID_CHAR_SHAPE_BG_BORDER_SIZE: ErrorCode = ErrorCode::new(1035);
pub const JID_CHAR_SHAPE_BG_BORDER_COLOR: ErrorCode = ErrorCode::new(1036);
pub const JID_CHAR_SHAPE_BG_COLOR: ErrorCode = ErrorCode::new(1037);
pub const JID_CHAR_SHAPE_BG_PATTONCOLOR: ErrorCode = ErrorCode::new(1038);
pub const JID_CHAR_SHAPE_BG_PATTONTYPE: ErrorCode = ErrorCode::new(1039);
pub const JID_CHAR_SHAPE_END: ErrorCode = ErrorCode::new(1040);

// ---- CHART ----
pub const JID_CHART: ErrorCode = ErrorCode::new(6300);

// ---- DOCSUMMARYINFO ----
pub const JID_DOCSUMMARYINFO: ErrorCode = ErrorCode::new(5000);

// ---- ENDNOTE ----
pub const JID_ENDNOTE: ErrorCode = ErrorCode::new(6100);

// ---- FOOTNOTE ----
pub const JID_FOOTNOTE: ErrorCode = ErrorCode::new(6000);

// ---- FORMOBJECT ----
pub const JID_FORMOBJECT: ErrorCode = ErrorCode::new(6700);

// ---- FORMULA ----
pub const JID_FORMULA: ErrorCode = ErrorCode::new(6500);

// ---- HYPERLINK ----
pub const JID_HYPERLINK: ErrorCode = ErrorCode::new(6900);
pub const JID_HYPERLINK_PERMISSION: ErrorCode = ErrorCode::new(6901);
pub const JID_HYPERLINK_END: ErrorCode = ErrorCode::new(6999);

// ---- MACRO ----
pub const JID_MACRO: ErrorCode = ErrorCode::new(7000);
pub const JID_MACRO_PERMISSION: ErrorCode = ErrorCode::new(7001);
pub const JID_MACRO_END: ErrorCode = ErrorCode::new(7099);

// ---- MEMO ----
pub const JID_MEMO: ErrorCode = ErrorCode::new(6200);

// ---- OLE ----
pub const JID_OLE: ErrorCode = ErrorCode::new(6600);

// ---- OUTLINESHAPE ----
pub const JID_OUTLINESHAPE: ErrorCode = ErrorCode::new(3200);
pub const JID_OUTLINESHAPE_TYPE: ErrorCode = ErrorCode::new(3201);
pub const JID_OUTLINESHAPE_STARTNUMBER: ErrorCode = ErrorCode::new(3202);
pub const JID_OUTLINESHAPE_VALUE: ErrorCode = ErrorCode::new(3203);
pub const JID_OUTLINESHAPE_LEVELTYPE: ErrorCode = ErrorCode::new(3204);
pub const JID_OUTLINESHAPE_LEVELTYPE_LEVEL: ErrorCode = ErrorCode::new(3205);
pub const JID_OUTLINESHAPE_LEVELTYPE_NUMBERTYPE: ErrorCode = ErrorCode::new(3206);
pub const JID_OUTLINESHAPE_LEVELTYPE_NUMBERSHAPE: ErrorCode = ErrorCode::new(3207);
pub const JID_OUTLINESHAPE_END: ErrorCode = ErrorCode::new(3299);

// ---- PAGE ----
pub const JID_PAGE: ErrorCode = ErrorCode::new(4000);
pub const JID_PAGE_TYPE: ErrorCode = ErrorCode::new(4001);
pub const JID_PAGE_WIDTH: ErrorCode = ErrorCode::new(4002);
pub const JID_PAGE_HEIGHT: ErrorCode = ErrorCode::new(4003);
pub const JID_PAGE_DIRECTION: ErrorCode = ErrorCode::new(4004);
pub const JID_PAGE_BOOKBINDING: ErrorCode = ErrorCode::new(4005);
pub const JID_PAGE_MARGIN_TOP: ErrorCode = ErrorCode::new(4006);
pub const JID_PAGE_MARGIN_HEADER: ErrorCode = ErrorCode::new(4007);
pub const JID_PAGE_MARGIN_LEFT: ErrorCode = ErrorCode::new(4008);
pub const JID_PAGE_MARGIN_BOOKBINDING: ErrorCode = ErrorCode::new(4009);
pub const JID_PAGE_MARGIN_RIGHT: ErrorCode = ErrorCode::new(4010);
pub const JID_PAGE_MARGIN_FOOT: ErrorCode = ErrorCode::new(4011);
pub const JID_PAGE_MARGIN_BOTTOM: ErrorCode = ErrorCode::new(4012);
pub const JID_PAGE_APPLYRANGE: ErrorCode = ErrorCode::new(4013);
pub const JID_PAGE_APPLYNEWDOC: ErrorCode = ErrorCode::new(4014);
pub const JID_PAGE_GRID_TYPE: ErrorCode = ErrorCode::new(4015);
pub const JID_PAGE_GRID_LINECOUNT: ErrorCode = ErrorCode::new(4016);
pub const JID_PAGE_GRID_LINESPACE: ErrorCode = ErrorCode::new(4017);
pub const JID_PAGE_GRID_GRADATION: ErrorCode = ErrorCode::new(4018);
pub const JID_PAGE_GRID_CHARSPACE: ErrorCode = ErrorCode::new(4019);
pub const JID_PAGE_GRID_ORTHOGRAPHY: ErrorCode = ErrorCode::new(4020);
pub const JID_PAGE_GRID_APPLYRANGE: ErrorCode = ErrorCode::new(4021);
pub const JID_PAGE_END: ErrorCode = ErrorCode::new(4999);

// ---- PARA ----
pub const JID_PARA_SHAPE: ErrorCode = ErrorCode::new(2000);
pub const JID_PARA_SHAPE_HORIZONTAL: ErrorCode = ErrorCode::new(2001);
pub const JID_PARA_SHAPE_MARGINLEFT: ErrorCode = ErrorCode::new(2002);
pub const JID_PARA_SHAPE_MARGINRIGHT: ErrorCode = ErrorCode::new(2003);
pub const JID_PARA_SHAPE_FIRSTLINE: ErrorCode = ErrorCode::new(2004);
pub const JID_PARA_SHAPE_INDENT: ErrorCode = ErrorCode::new(2005);
pub const JID_PARA_SHAPE_OUTDENT: ErrorCode = ErrorCode::new(2006);
pub const JID_PARA_SHAPE_LINESPACING: ErrorCode = ErrorCode::new(2007);
pub const JID_PARA_SHAPE_LINESPACINGVALUE: ErrorCode = ErrorCode::new(2008);
pub const JID_PARA_SHAPE_SPACINGPARAUP: ErrorCode = ErrorCode::new(2009);
pub const JID_PARA_SHAPE_SPACINGPARABOTTOM: ErrorCode = ErrorCode::new(2010);
pub const JID_PARA_SHAPE_SPACINGGRIDPAPER: ErrorCode = ErrorCode::new(2011);
pub const JID_PARA_SHAPE_LINEBREAKKOREAN: ErrorCode = ErrorCode::new(2012);
pub const JID_PARA_SHAPE_LINEBREAKENGLISH: ErrorCode = ErrorCode::new(2013);
pub const JID_PARA_SHAPE_LINEBREAKCONDENSE: ErrorCode = ErrorCode::new(2014);
pub const JID_PARA_SHAPE_PARATYPE: ErrorCode = ErrorCode::new(2015);
pub const JID_PARA_SHAPE_PARATYPEVALUE: ErrorCode = ErrorCode::new(2016);
pub const JID_PARA_SHAPE_WIDOWORPHAN: ErrorCode = ErrorCode::new(2017);
pub const JID_PARA_SHAPE_KEEPWITHNEXT: ErrorCode = ErrorCode::new(2018);
pub const JID_PARA_SHAPE_KEEPLINESTOGETHER: ErrorCode = ErrorCode::new(2019);
pub const JID_PARA_SHAPE_PAGEBREAKBEFORE: ErrorCode = ErrorCode::new(2020);
pub const JID_PARA_SHAPE_FONTLINEHEIGHT: ErrorCode = ErrorCode::new(2021);
pub const JID_PARA_SHAPE_LINEWRAP: ErrorCode = ErrorCode::new(2022);
pub const JID_PARA_SHAPE_AUTOSPACEEASIANENG: ErrorCode = ErrorCode::new(2023);
pub const JID_PARA_SHAPE_AUTOSPACEEASIANNUM: ErrorCode = ErrorCode::new(2024);
pub const JID_PARA_SHAPE_VERTICALALIGN: ErrorCode = ErrorCode::new(2025);
pub const JID_PARA_SHAPE_TABTYPES: ErrorCode = ErrorCode::new(2026);
pub const JID_PARA_SHAPE_TABTYPE: ErrorCode = ErrorCode::new(2027);
pub const JID_PARA_SHAPE_TABSHAPE: ErrorCode = ErrorCode::new(2028);
pub const JID_PARA_SHAPE_TABPOSITION: ErrorCode = ErrorCode::new(2029);
pub const JID_PARA_SHAPE_AUTOTABINDENT: ErrorCode = ErrorCode::new(2030);
pub const JID_PARA_SHAPE_AUTOTABPARARIGHTEND: ErrorCode = ErrorCode::new(2031);
pub const JID_PARA_SHAPE_BASETABSPACE: ErrorCode = ErrorCode::new(2032);
pub const JID_PARA_SHAPE_BORDER: ErrorCode = ErrorCode::new(2033);
pub const JID_PARA_SHAPE_BORDERPOSITION: ErrorCode = ErrorCode::new(2034);
pub const JID_PARA_SHAPE_BORDERTYPE: ErrorCode = ErrorCode::new(2035);
pub const JID_PARA_SHAPE_BORDERSIZE: ErrorCode = ErrorCode::new(2036);
pub const JID_PARA_SHAPE_BORDERCOLOR: ErrorCode = ErrorCode::new(2037);
pub const JID_PARA_SHAPE_BGCOLOR: ErrorCode = ErrorCode::new(2038);
pub const JID_PARA_SHAPE_BGPATTONCOLOR: ErrorCode = ErrorCode::new(2039);
pub const JID_PARA_SHAPE_BGPATTONTYPE: ErrorCode = ErrorCode::new(2040);
pub const JID_PARA_SHAPE_SPACINGLEFT: ErrorCode = ErrorCode::new(2041);
pub const JID_PARA_SHAPE_SPACINGRIGHT: ErrorCode = ErrorCode::new(2042);
pub const JID_PARA_SHAPE_SPACINGTOP: ErrorCode = ErrorCode::new(2043);
pub const JID_PARA_SHAPE_SPACINGBOTTOM: ErrorCode = ErrorCode::new(2044);
pub const JID_PARA_SHAPE_SPACINGIGNORE: ErrorCode = ErrorCode::new(2045);
pub const JID_PARA_SHAPE_END: ErrorCode = ErrorCode::new(2999);

// ---- PARANUMBULLET ----
pub const JID_PARANUMBULLET: ErrorCode = ErrorCode::new(3400);
pub const JID_PARANUMBULLET_TYPE: ErrorCode = ErrorCode::new(3401);
pub const JID_PARANUMBULLET_STARTNUMBER: ErrorCode = ErrorCode::new(3402);
pub const JID_PARANUMBULLET_VALUE: ErrorCode = ErrorCode::new(3403);
pub const JID_PARANUMBULLET_LEVELTYPE: ErrorCode = ErrorCode::new(3404);
pub const JID_PARANUMBULLET_LEVELTYPE_LEVEL: ErrorCode = ErrorCode::new(3405);
pub const JID_PARANUMBULLET_LEVELTYPE_NUMBERTYPE: ErrorCode = ErrorCode::new(3406);
pub const JID_PARANUMBULLET_LEVELTYPE_NUMBERSHAPE: ErrorCode = ErrorCode::new(3407);
pub const JID_PARANUMBULLET_END: ErrorCode = ErrorCode::new(3499);

// ---- SPECIALCHARACTER ----
pub const JID_SPECIALCHARACTER: ErrorCode = ErrorCode::new(3100);
pub const JID_SPECIALCHARACTER_MINIMUM: ErrorCode = ErrorCode::new(3101);
pub const JID_SPECIALCHARACTER_MAXIMUM: ErrorCode = ErrorCode::new(3102);
pub const JID_SPECIALCHARACTER_END: ErrorCode = ErrorCode::new(3199);

// ---- STYLE ----
pub const JID_STYLE: ErrorCode = ErrorCode::new(3500);
pub const JID_STYLE_TYPE: ErrorCode = ErrorCode::new(3501);
pub const JID_STYLE_PERMISSION: ErrorCode = ErrorCode::new(3502);
pub const JID_STYLE_END: ErrorCode = ErrorCode::new(3599);

// ---- TABLE ----
pub const JID_TABLE: ErrorCode = ErrorCode::new(3000);
pub const JID_TABLE_SIZEWIDTH: ErrorCode = ErrorCode::new(3001);
pub const JID_TABLE_SIZEHEIGHT: ErrorCode = ErrorCode::new(3002);
pub const JID_TABLE_SIZEFIXED: ErrorCode = ErrorCode::new(3003);
pub const JID_TABLE_TREATASCHAR: ErrorCode = ErrorCode::new(3004);
pub const JID_TABLE_POS: ErrorCode = ErrorCode::new(3005);
pub const JID_TABLE_TEXTPOS: ErrorCode = ErrorCode::new(3006);
pub const JID_TABLE_HTYPE: ErrorCode = ErrorCode::new(3007);
pub const JID_TABLE_HDIRECTION: ErrorCode = ErrorCode::new(3008);
pub const JID_TABLE_HVALUE: ErrorCode = ErrorCode::new(3009);
pub const JID_TABLE_VTYPE: ErrorCode = ErrorCode::new(3010);
pub const JID_TABLE_VDIRECTION: ErrorCode = ErrorCode::new(3011);
pub const JID_TABLE_VVALUE: ErrorCode = ErrorCode::new(3012);
pub const JID_TABLE_SOFLOWWITHTEXT: ErrorCode = ErrorCode::new(3013);
pub const JID_TABLE_SOALLOWOVERLAP: ErrorCode = ErrorCode::new(3014);
pub const JID_TABLE_SOHOLDANCHOROBJ: ErrorCode = ErrorCode::new(3015);
pub const JID_TABLE_PARALLEL: ErrorCode = ErrorCode::new(3016);
pub const JID_TABLE_ROTATION: ErrorCode = ErrorCode::new(3017);
pub const JID_TABLE_GRADIENT_H: ErrorCode = ErrorCode::new(3018);
pub const JID_TABLE_GRADIENT_V: ErrorCode = ErrorCode::new(3019);
pub const JID_TABLE_NUMVERTYPE: ErrorCode = ErrorCode::new(3020);
pub const JID_TABLE_OBJPROTECT: ErrorCode = ErrorCode::new(3021);
pub const JID_TABLE_MARGIN_LEFT: ErrorCode = ErrorCode::new(3022);
pub const JID_TABLE_MARGIN_RIGHT: ErrorCode = ErrorCode::new(3023);
pub const JID_TABLE_MARGIN_TOP: ErrorCode = ErrorCode::new(3024);
pub const JID_TABLE_MARGIN_BOTTOM: ErrorCode = ErrorCode::new(3025);
pub const JID_TABLE_CAPTION_POSITION: ErrorCode = ErrorCode::new(3026);
pub const JID_TABLE_CAPTION_SIZE: ErrorCode = ErrorCode::new(3027);
pub const JID_TABLE_CAPTION_SPACING: ErrorCode = ErrorCode::new(3028);
pub const JID_TABLE_CAPTION_SOCAPFULLSIZE: ErrorCode = ErrorCode::new(3029);
pub const JID_TABLE_CAPTION_LINEWRAP: ErrorCode = ErrorCode::new(3030);
pub const JID_TABLE_BORDER: ErrorCode = ErrorCode::new(3031);
pub const JID_TABLE_BORDER_POSITION: ErrorCode = ErrorCode::new(3032);
pub const JID_TABLE_BORDER_TYPE: ErrorCode = ErrorCode::new(3033);
pub const JID_TABLE_BORDER_SIZE: ErrorCode = ErrorCode::new(3034);
pub const JID_TABLE_BORDER_COLOR: ErrorCode = ErrorCode::new(3035);
pub const JID_TABLE_BORDER_CELLSPACING: ErrorCode = ErrorCode::new(3036);
pub const JID_TABLE_BGFILL_TYPE: ErrorCode = ErrorCode::new(3037);
pub const JID_TABLE_BGFILL_FACECOLOR: ErrorCode = ErrorCode::new(3038);
pub const JID_TABLE_BGFILL_PATTONCOLOR: ErrorCode = ErrorCode::new(3039);
pub const JID_TABLE_BGFILL_PATTONTYPE: ErrorCode = ErrorCode::new(3040);
pub const JID_TABLE_BGGRADATION_STARTCOLOR: ErrorCode = ErrorCode::new(3041);
pub const JID_TABLE_BGGRADATION_ENDCOLOR: ErrorCode = ErrorCode::new(3042);
pub const JID_TABLE_BGGRADATION_TYPE: ErrorCode = ErrorCode::new(3043);
pub const JID_TABLE_BGGRADATION_WIDTHCENTER: ErrorCode = ErrorCode::new(3044);
pub const JID_TABLE_BGGRADATION_HEIGHTCENTER: ErrorCode = ErrorCode::new(3045);
pub const JID_TABLE_BGGRADATION_GRADATIONANGLE: ErrorCode = ErrorCode::new(3046);
pub const JID_TABLE_BGGRADATION_BLURLEVEL: ErrorCode = ErrorCode::new(3047);
pub const JID_TABLE_BGGRADATION_BLURCENTER: ErrorCode = ErrorCode::new(3048);
pub const JID_TABLE_PICTURE_FILE: ErrorCode = ErrorCode::new(3049);
pub const JID_TABLE_PICTURE_INCLUDE: ErrorCode = ErrorCode::new(3050);
pub const JID_TABLE_PICTUREFILL_TYPE: ErrorCode = ErrorCode::new(3051);
pub const JID_TABLE_PICTUREFILL_VALUE: ErrorCode = ErrorCode::new(3052);
pub const JID_TABLE_EFFECT_TYPE: ErrorCode = ErrorCode::new(3053);
pub const JID_TABLE_EFFECT_VALUE: ErrorCode = ErrorCode::new(3054);
pub const JID_TABLE_WATERMARK: ErrorCode = ErrorCode::new(3055);
pub const JID_TABLE_TABLE_IN_TABLE: ErrorCode = ErrorCode::new(3056);
pub const JID_TABLE_END: ErrorCode = ErrorCode::new(3999);

// ---- WORDART ----
pub const JID_WORDART: ErrorCode = ErrorCode::new(6400);

